### ISSUE TITLE
SPI Class not referenced correctly?

### ISSUE THREAD

**Issue by andrethomas** [palmerr23/STM32F01-ILI9486-RPi-Driver#1]
Looks like there may be a compatibility issue between the SPI class used in Arduino_STM32 and the library for the ILI9486 provided here - planning on fixing it? :)

Adafruit_ILI9486_STM32.cpp: In function 'void writedata16(uint16_t, uint32_t)':
Adafruit_ILI9486_STM32.cpp:41:22: error: invalid conversion from 'uint16_t {aka short unsigned int}' to 'const uint8* {aka const unsigned char*}' [-fpermissive]

 SPI.write(color, num);

**Comment by andrethomas** [comment]
Fixed by using updated SPI code from https://github.com/stevstrong/Arduino_STM32/tree/master/STM32F1/libraries/SPI - Not sure why its not in the main

**Comment by palmerr23** [comment]
Thanks for the heads up and finding the solution (minime &  Steve). 
I hope you enjoy the code.
